config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  
  # 渡された文字列のハッシュ化
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムな文字列を返す。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続化セッションのためにremember_digestを保存する。
  def remember
    self.remember_token = User.new_token # 認証に必要な仮属性のremember_tokenにハッシュ化する前の値を入れている。
    update_attribute(:remember_digest, User.digest(remember_token))  # remember_digestにremember_tokenをハッシュ化したものを入れて更新
  end
  
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # remember_tokenとremember_digestの認証に使う。 トークンとダイジェストが一致すれば、true
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [ :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :log_in_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :admin_or_correct_user, only: [:show, :edit, :update]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show
  
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  def index
    @users = User.paginate(page: params[:page]).search(params[:search]).order(:id)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params_user)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーを新規作成しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(params_user)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザー情報の更新に失敗しました。"
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_path
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
      redirect_to users_path
    else
      flash[:danger] = "#{@user.name}の更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      render :edit_basic_info
    end
  end
  
  
  
  private
  
    def params_user
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit( :base_time, :work_time )
    end
    
    
    def admin_or_correct_user
      unless current_user.admin? || current_user?(@user)
        flash[:danger] = "権限がありません。"
        redirect_to root_url
      end
    end
    
    
  
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
  def wday_class(day)
    if day.worked_on.wday == 0
      "danger"
    elsif day.worked_on.wday == 6
      "info"
    end
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
   <%= render 'shared/error_message' %>
    
   <%= f.label :name, class: "label-#{yield(:class_text)}" %>
   <%= f.text_field :name, class: "form-control" %>
      
   <%= f.label :email, class: "label-#{yield(:class_text)}" %>
   <%= f.email_field :email, class: "form-control" %>
   
   <%= f.label :department, class: "label-#{yield(:class_text)}" %>
   <%= f.text_field :department, class: "form-control" %>
      
   <%= f.label :password, class: "label-#{yield(:class_text)}" %>
   <%= f.password_field :password, class: "form-control" %>
      
   <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
   <%= f.password_field :password_confirmation, class: "form-control" %>
      
   <%= f.submit yield(:button), class: "btn btn-block btn-primary btn-signup" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, @user.name + 'の更新') %>
<% provide(:class_text, 'edit') %>
<% provide(:button, '更新') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報の更新") %>
<h1>基本情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user), method: :patch, local: true) do |f| %>
      
      <%= f.label :basic_time, class: "label-signup" %>
      <%= f.time_field :basic_time, class: "form-control" %>
      
      <%= f.label :work_time, class: "label-signup" %>
      <%= f.time_field :work_time, class: "form-control" %>
      
      <%= f.submit "編集", class: "btn btn-primary btn-block btn-signup" %>
    <% end %>
      
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧ページ") %>
<h1>ユーザー一覧</h1>
<div class="text-right">
  <%= form_tag(users_path,method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag "検索" %>
  <% end %>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= will_paginate %>
    <table class="table table-condensed ">
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td ><%= link_to user.name, user_path(user) %></td>
            <td class="text-right"><%= link_to "基本情報編集", edit_basic_info_user_path(user), class: "btn btn-success" %>
                <%= link_to "削除", user, method: :delete, 
                class: "btn btn-danger", data: { confirm: "削除してよろしいですか？"} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "新規アカウント作成") %>
<% provide(:class_text, 'signup') %>
<% provide(:button, "新規作成") %>
<h1>アカウント作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-condensed table-bordered user-table">
    <tr>
      <td width="400">
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-default" %>
        <%= l(@first_day,format: :middle) %> 時間管理表
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-default"%>
      </td>
      <td width="250">指定勤務時間<%= format_basic_info(@user.work_time) %></td>
      <td colspan="3">基本勤務時間<%= format_basic_info(@user.basic_time) %></td>
      <td width="100">初日<%= l(@first_day,format: :short) %></td>
    </tr>
    <tr>
      <td>所属:<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前:<%= @user.name %></td>
      <td>コード</td>
      <td></td>
      <td>出勤日数:<%= @worked_sum %>日</td>
      <td>締め<%= l(@last_day,format: :short) %></td>
    </tr>
  </table>
  
  <div class="btn-users-show">
    <%= link_to "一ヶ月の勤怠編集へ", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-info" %>
  </div>
  
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="2">日付</th>
        <th rowspan="2">曜日</th>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="text-<%= wday_class(day) %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= l(day.started_at.floor_to(15.minutes), format: :min) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
          <td><%= l(day.finished_at.floor_to(15.minutes), format: :min) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= stf_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
              <% @total_working_times = @total_working_times.to_f + stf_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="2">累計在社時間</td>
        <td rowspan="2"></td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="2"><%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </tfoot>
  </table>
</div>